title: "Krew â€“ kubectl plugin manager"
baseURL: "https://krew.sigs.k8s.io/"
languageCode: "en-us"
enableGitInfo: true
enableRobotsTXT: true
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  highlight:
    style: dracula
